# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path:             fos_user_security_check
                default_target_path:            user_dispatch
                always_use_default_target_path: false
            logout:       
                target: fos_user_security_login
            anonymous:    true
            remember_me:
                 key:  "%secret%"
                 lifetime: 86400
                 path:     /
                 domain:   ~
                 user_provider: fos_userbundle
